### ISSUE TITLE
Corelation to the Pet Pals and Dragon Kingdom McDonalds CDs?

### ISSUE THREAD

**Issue by KelvinGuy1** [BLiNXthetimesweeperGOD/LeapFrog-Tools#3]
I stumbled across pc releases of pet pals and dragon kingdom. They seem to be ports based of the same rom. It seems like some aspect match up between these and the roms like the swf files give or take a few that were changed to remove features to make this a demo (this leaves a lot of content unused in these games). Do you think these have major correlations to the structure of a leapster roms?

https://archive.org/details/leapster-2-dragon-kingdom

**Comment by BLiNXthetimesweeperGOD** [comment]
No, sadly. The "emulator" in these is also just a flash player with a custom script inside that points to all of the files it needs to load.
